version: 2

jobs:

  # Building and testing the project
  # Useful when a PR is open, for example
  build-and-test:
    docker:
      - image: circleci/python:3.8.0

    steps:
      - checkout
      - restore_cache:
          keys: 
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths: 
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run Pytest
          command: |
            poetry run pytest tests/

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test
